/** Default context provider set (H10, plan §16.4) — registration order is
 *  the collection order; layer+priority drive final message order. */

import type { ContextProvider } from "../../contracts/context"
import { LANG_INSTRUCTION_PROVIDER, STABLE_MEMORY_PROVIDER, PROJECT_KERNEL_PROVIDER, CONTEXT_MAP_PROVIDER, SKILLS_PROVIDER } from "./stable"
import { PLAN_STATE_PROVIDER, RESEARCH_PROVIDER } from "./plan"
import { STAGED_CONTEXT_PROVIDER, THINKING_PROVIDER, KNOWLEDGE_PROVIDER, PLANNING_PROVIDER, MODE_CONTRACT_PROVIDER, CONVERSATION_TAIL_PROVIDER } from "./volatile"

export function createDefaultContextProviders(): ContextProvider[] {
  return [
    LANG_INSTRUCTION_PROVIDER,
    STABLE_MEMORY_PROVIDER,
    PROJECT_KERNEL_PROVIDER,
    CONTEXT_MAP_PROVIDER,
    SKILLS_PROVIDER,
    PLAN_STATE_PROVIDER,
    RESEARCH_PROVIDER,
    STAGED_CONTEXT_PROVIDER,
    THINKING_PROVIDER,
    KNOWLEDGE_PROVIDER,
    PLANNING_PROVIDER,
    MODE_CONTRACT_PROVIDER,
    CONVERSATION_TAIL_PROVIDER,
  ]
}

export {
  LANG_INSTRUCTION_PROVIDER,
  STABLE_MEMORY_PROVIDER,
  PROJECT_KERNEL_PROVIDER,
  CONTEXT_MAP_PROVIDER,
  SKILLS_PROVIDER,
  PLAN_STATE_PROVIDER,
  RESEARCH_PROVIDER,
  STAGED_CONTEXT_PROVIDER,
  THINKING_PROVIDER,
  KNOWLEDGE_PROVIDER,
  PLANNING_PROVIDER,
  MODE_CONTRACT_PROVIDER,
  CONVERSATION_TAIL_PROVIDER,
}
